# 池化层 Pooling Layer，池化层的提出是为了缓解卷积层对位置的过度敏感性

In [1]:
import mxnet as mx
from mxnet import nd
from mxnet import gluon,autograd
from mxnet.gluon import nn

C:\Users\lenovo\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [5]:
def pool2d(X,pool_size,mode='max'):
    p_h,p_w = pool_size
    Y = nd.zeros((X.shape[0]-p_h+1,X.shape[1]-p_w+1),ctx=mx.gpu())
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            if mode=='max':
                Y[i,j] = X[i:i+p_h,j:j+p_w].max()
            elif mode=='avg':
                Y[i,j] = X[i:i+p_h,j:j+p_w].mean()
    return Y

In [6]:
X = nd.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]],ctx=mx.gpu())
pool2d(X,(2,2))


[[4. 5.]
 [7. 8.]]
<NDArray 2x2 @gpu(0)>

In [7]:
pool2d(X,(2,2),'avg')


[[2. 3.]
 [5. 6.]]
<NDArray 2x2 @gpu(0)>

## 填充和步幅，通卷积层一样，池化层也可以在输入的高和宽的两侧进行填充并调整窗口的移动步幅来改变输出的形状

In [11]:
X= nd.arange(16,ctx=mx.gpu()).reshape((1,1,4,4))

In [12]:
pool2d = nn.MaxPool2D(3)
pool2d(X)


[[[[10.]]]]
<NDArray 1x1x1x1 @gpu(0)>

In [15]:
pool2d = nn.MaxPool2D(3,padding=1,strides=2)
pool2d(X)


[[[[ 5.  7.]
   [13. 15.]]]]
<NDArray 1x1x2x2 @gpu(0)>

## 多通道时，池化层对每个输入通道分别进行池化，而不是像卷积层那样将各通道的输入按通道相加

In [16]:
X = nd.concat(X,X+1,dim=1)

In [17]:
X


[[[[ 0.  1.  2.  3.]
   [ 4.  5.  6.  7.]
   [ 8.  9. 10. 11.]
   [12. 13. 14. 15.]]

  [[ 1.  2.  3.  4.]
   [ 5.  6.  7.  8.]
   [ 9. 10. 11. 12.]
   [13. 14. 15. 16.]]]]
<NDArray 1x2x4x4 @gpu(0)>

In [18]:
#输出通道数仍然是2

pool2d = nn.MaxPool2D(3, padding=1, strides=2)
pool2d(X)


[[[[ 5.  7.]
   [13. 15.]]

  [[ 6.  8.]
   [14. 16.]]]]
<NDArray 1x2x2x2 @gpu(0)>